### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by noisytoken** [Apress/practical-docker-with-python#11]
I am at the end of chapter 4 when I try to run `docker run --name subreddit_fetcher_bot sathyabhat:subreddit_fetcher`, I see no output.

I am using files in [this](https://github.com/Apress/practical-docker-with-python/tree/master/docker%20subreddit%20fetcher) directory. Nothing is modified except the `token`  in the `Dockerfile`

When I try to run the application after creating virtualenv (without dockerizing it) I get this error:

```bash
(env) x@x-desktop:~/tmp/docker subreddit fetcher$ BOT_KEY=my_token python newsbot.py 
Traceback (most recent call last):
  File "newsbot.py", line 24, in <module>
    handle_incoming_messages(States.last_updated)
  File "/home/x/tmp/docker subreddit fetcher/telegram.py", line 37, in handle_incoming_messages
    r = get_updates(last_updated)
  File "/home/x/tmp/docker subreddit fetcher/telegram.py", line 15, in get_updates
    response = requests.get(API_BASE + BOT_KEY + '/getUpdates', params={'offset': last_updated+1})
TypeError: must be str, not NoneType
(env) x@x-desktop:~/tmp/docker subreddit fetcher$ 
```

**Comment by SathyaBhat** [comment]
@noisytoken  thanks for the report. Did you build the docker image first? Can you post a screenshot of what happens when you run the container with ` docker run --name subreddit_fetcher_bot sathyabhat:subreddit_fetcher`? 

Can you run and post the contents of `docker logs subreddit_fetcher_bot`?

**Comment by noisytoken** [comment]
When I execute `docker run --name subreddit_fetcher_bot sathyabhat:subreddit_fetcher`. I see no output:

![image](https://user-images.githubusercontent.com/6175606/66106753-4681fa80-e5dc-11e9-9226-114a600222a9.png)

Looks like the terminal is just waiting.

Further, `docker logs subreddit_fetcher_bot` also doesn' t show any logs.

![image](https://user-images.githubusercontent.com/6175606/66106891-9791ee80-e5dc-11e9-8b34-6263384dc5e7.png)

**Comment by noisytoken** [comment]
Now, I am at the end of chapter 5, when I run the `docker run --name subreddit_fetcher_volume -v subreddit_fetcher:/apps/subredditfetcher sathyabhat:subreddit_fetcher_volume ` command I get  api.telegram.org:443.

![image](https://user-images.githubusercontent.com/6175606/66152830-ee78e180-e637-11e9-87ba-e342923b78a9.png)

**Comment by SathyaBhat** [comment]
@noisytoken this flew under the radar - are you still having issues?
