### ISSUE TITLE
Alpine doesn't reinstall cached files, it can't install pandas

### ISSUE THREAD

**Issue by leolle** [Apress/practical-docker-with-python#12]
In the content A LOOK AT SLIM DOCKER RELEASE IMAGE (USING MULTI-STAGE BUILDS)
Dockerfile Listing
```
FROM python:3 as python-base
COPY requirements.txt .
RUN pip install -r requirements.txt
FROM python:3-alpine
COPY --from=python-base /root/.cache /root/.cache
Chapter 4 Understanding the doCkerfile87
COPY --from=python-base requirements.txt .
RUN pip install -r requirements.txt && rm -rf /root/.cache
```
_copy the files installed from the first stage, reinstall
them (notice this time, pip fetches the cached files and doesn’t build them
again), and then delete the cached install files._

I have pandas and numpy within my dependencies.
When I build the dockerfile it will not install pandas from /root/.cache. And it even can't install pandas from bash within the container.

**Comment by SathyaBhat** [comment]
do you have them listed in `requirements.txt`? Do you have a repo or a paste the contents of `requirements.txt`?
