### ISSUE TITLE
missing documentation in the book

### ISSUE THREAD

**Issue by ms82494** [Apress/practical-docker-with-python#14]
Hi,

I am reading the electronic version of your book on Scribd, so maybe that's abridged and my notes don't apply to the paper version. Just in case they do, 
1. I saw no mention of this repo in the text. So when I read on p.46 ```pip3 install -r requirements.txt``` I was wondering which requirements.txt file you were referring to. I went to the APress site on a hunch and found the link to the downloads there.
2. Just following along, once I had the bot set up and issued the first ```/fetch``` order, the bot threw an error message because I didn't have a Reddit Client ID or Client Secret (see screenshot)
![Screenshot 2020-04-26 at 3 25 24 PM](https://user-images.githubusercontent.com/6218876/80321482-36c54000-87d2-11ea-9696-956c238f8304.png)

The error message is fortunately descriptive, so I was able to generate those. But that step could have been documented.

Other than that, I really enjoy the book.

Thanks,
Matt

**Comment by SathyaBhat** [comment]
Hi Matt, 

Thank you for the feedback. 

1. Yes, that was an oversight
2. Reddit made auth mandatory shortly after the book was published, so I put in the detailed error message so that readers could fix it.

I am glad you liked the book.

(ps: I had no idea the book was on scribd)
