### ISSUE TITLE
Add missing Key in the json_response dictionary

### ISSUE THREAD

**Issue by Bernstein7z** [Apress/practical-docker-with-python#18]
By editing the message it throws a TypeError. The reason is missing of the key `req` at this row:

https://github.com/Apress/practical-docker-with-python/blob/731f8ba9f99e2d167b331a79592141c73e74e04d/source-code/chapter-3/python-app/telegram.py#L56

please add it.
thx

**Comment by SathyaBhat** [comment]
thanks for the reporting. I'll check and update

**Comment by SathyaBhat** [comment]
fixed with #19
