### ISSUE TITLE
Getting exception while running chapter-3 module

### ISSUE THREAD

**Issue by srivastavakushagra999** [Apress/practical-docker-with-python#24]
Not able to connect to reddit. If you have sen this issue before

```
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.reddit.com', port=443): 

Max retries exceeded with url: /r/test/top.json?limit=5 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
```

**Comment by SathyaBhat** [comment]
this looks like an environment or network error, works as expected

![image](https://user-images.githubusercontent.com/25424/150175799-f935bfe9-602f-40c0-bef9-06d8a4771546.png)


please see https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error or similar questions
