### ISSUE TITLE
Chapter 5 excercise 2 error

### ISSUE THREAD

**Issue by explodinghat** [Apress/practical-docker-with-python#25]
Getting the below error when trying to build the dockerfile in chapter 5 ex 2:

> [5/5] RUN pip install -r requirements.txt:                                                                                                                                         
#8 4.700 Collecting peewee==2.10.2                                                                                                                                                    
#8 4.940   Downloading peewee-2.10.2.tar.gz (516 kB)                                                                                                                                  
#8 5.008      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 516.1/516.1 KB 9.7 MB/s eta 0:00:00                                                                                             
#8 5.103   Preparing metadata (setup.py): started                                                                                                                                     
#8 5.879   Preparing metadata (setup.py): finished with status 'error'
#8 5.906   error: subprocess-exited-with-error
#8 5.906   
#8 5.906   × python setup.py egg_info did not run successfully.
#8 5.906   │ exit code: 1
#8 5.906   ╰─> [10 lines of output]
#8 5.906       /tmp/pip-install-bhpn8q8f/peewee_5353c5985ec14e7f815c7fe81f7e544d/setup.py:21: UserWarning: Cython C extensions for peewee will NOT be built, because Cython does not seem to be installed. To enable Cython C extensions, install Cython >=0.22.1.
#8 5.906         warnings.warn('Cython C extensions for peewee will NOT be built, because '
#8 5.906       Traceback (most recent call last):
#8 5.906         File "<string>", line 2, in <module>
#8 5.906         File "<pip-setuptools-caller>", line 34, in <module>
#8 5.906         File "/tmp/pip-install-bhpn8q8f/peewee_5353c5985ec14e7f815c7fe81f7e544d/setup.py", line 64, in <module>
#8 5.906           version=__import__('peewee').__version__,
#8 5.906         File "/tmp/pip-install-bhpn8q8f/peewee_5353c5985ec14e7f815c7fe81f7e544d/peewee.py", line 124, in <module>
#8 5.906           from collections import Callable
#8 5.906       ImportError: cannot import name 'Callable' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
#8 5.906       [end of output]
#8 5.906   
#8 5.906   note: This error originates from a subprocess, and is likely not a problem with pip.
#8 5.909 error: metadata-generation-failed
#8 5.909 
#8 5.909 × Encountered error while generating package metadata.
#8 5.909 ╰─> See above for output.
#8 5.909 
#8 5.909 note: This is an issue with the package mentioned above, not pip.
#8 5.909 hint: See above for details.
#8 6.162 WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
#8 6.162 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

Same error occurs if I add a line 'RUN ["pip", "install", "--upgrade", "pip"]' to the dockerfile and if I add Cython=0.22.1 to requirements.txt

Also note that this version of the file differs significantly from the version in the book, but is erroring out on the requirements install line which is no different between this repo + the book version.

**Comment by SathyaBhat** [comment]
Hi @explodinghat - thank you for reporting. I'll check and update here.

**Comment by SathyaBhat** [comment]
Hi @explodinghat 

I've fixed this in chapter 5 & 7 exercises, please change the base Docker image - the first line of the Dockerfile must read 

```
FROM python:3.7-alpine
```

Thanks for reporting!
